language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true

# TODO: Debug & Release modes

install:
  - |
    if [ "${TRAVIS_OS_NAME}" == 'linux' ]; then
      sudo apt-get --no-install-recommends install texinfo texi2html texlive-base texlive-generic-recommended texlive-fonts-recommended doxygen graphviz texlive-latex-base texlive-latex-recommended texlive-latex-extra python-git
    else
      brew install texinfo
      brew ln texinfo --force
      brew upgrade cmake
    fi

script:
  - |
    srcdir='..'
    mkdir build
    cd build
    cmake -DBUILD_DOC=ON -DBUILD_TESTING=ON -DDISABLE_REFMAN_PDF=ON ..

  - make lib
  - make check-testsuite     # Build and check the testsuite
  - make check-examples      # Build and check the examples
    # TODO! (fails with error: no such file or directory: 'arrdaxpyf.o')
    # - make check-benchmarks    # Build and check the benchmarks (takes a long time)
  - make blitz-doc

  - sudo make install        # Install Blitz++

  - |
    if [ "${TRAVIS_OS_NAME}" == 'linux' ]; then
       LD_LIBRARY_PATH=/usr/local/lib ${srcdir}/travis-ci/check-wiki-examples.py
    fi
